model:
  name: efficientnet
  args:
    num_classes: 5
    pretrained: True  # Use pre-trained ResNet50 weights
    learning_rate: 0.01
    batch_size: 4
    num_workers: 2
    num_epochs: 10

data:
  data_root: data
  train_csv: data/train.csv
  test_csv: data/test.csv
  
